version: '3.8'
services:
  api:
    container_name: es-ojt-api-diane
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Seoul
    env_file:
      - .env
    volumes:
      - /mnt/disks/data/qa42/esojt/api/diane/src:/es-ojt-diane/src
      - /mnt/disks/data/qa42/esojt/api/diane/log:/log/api
    network_mode: "host"
    restart: always